<a href="https://colab.research.google.com/github/Abdulrahman-M-Rezk/Cis_Tasks/blob/main/solution_of_Numpy_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Task_2 Numpy
# **Abdulrahman Mohamed Rizk**

> Try to solve these questions by yourself, and if you need any help you can ask your mentor Eng. Hossam Taha (On Discord: hossamtaha) or Any Supervisor--> Eng. Zainab El Sayed (On Discord: zainab_elsayed1) or Eng. Areej Elshebly (On Discord: areja52) or Eng. Mohamed Ehab (On Discord: moe0000)

> You can also search but Don't use AI tools like Chat GPT!

# **Q1) Let's Make Some Brain Storming With Indexing!**

In [ ]:
# Extract "hello" from the given nested list
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

In [ ]:
print(lst[3][1][2][0])

hello


# **Q2) Import Numpy Package.**

In [ ]:
import numpy as np

# **Q3) Write a Numpy Program to Create 3x3 matrix with values ranging from 2 to 10.**

In [ ]:
np.random.uniform(2,10,(3,3))

array([[5.04810741, 8.67733181, 6.93895446],
       [7.77100645, 3.19165516, 3.07079201],
       [5.07533768, 8.28054404, 9.51048009]])

# **Q4) Write a Program to Create an Array of Random Integer Numbers (shape 3x4).**

In [ ]:
np.random.randint(1,50, (3,4))

array([[ 3,  5, 37,  1],
       [ 3, 16, 16, 20],
       [39, 31,  7, 33]])

# **Q5) Use NumPy's np.array() function to convert both a list and a tuple into arrays.**

In [ ]:
lst = [[1,2],[3,4],[5,100],[200,23],[1,7]]
arr_1 = np.array(lst)
arr_1

array([[  1,   2],
       [  3,   4],
       [  5, 100],
       [200,  23],
       [  1,   7]])

In [ ]:
tupl = (2,3,5,7)
np.array(tupl)

array([2, 3, 5, 7])

# **Q6) Get the Data Type of the Following Array.**

In [ ]:
arr = np.array([1, 2, 3, 4])

In [ ]:
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


# **Q7) Change the Data Type of 'arr' Array to 'int16'.**

In [ ]:
arr.dtype = np.int16
arr.dtype

dtype('int16')